### ISSUE TITLE
If a waiting string does not have a semi colon in the middle of the sentense, then no warning is shown

### ISSUE THREAD

**Issue by psmits1567** [vlad-timotei/wpgp-tools#14]
The add-on checks for missing semi colon at the end of the sentence. It would be good to check the presence of a semi colon everywhere within the sentence, and throw an error if one is missing.
Example:
https://translate.wordpress.org/projects/wp-themes/gridbox/nl/formal/?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=3344973&filters%5Btranslation_id%5D=45467476
![afbeelding](https://user-images.githubusercontent.com/28138634/124619784-3c5bf280-de79-11eb-83bb-a20a23f6e6f8.png)
Original:
Search Results for: %s
Translation missing the ":"
Zoek resultaten voor %s

**Comment by vlad-timotei** [comment]
Was thinking about including this in v.1.4, but also trying not to overpopulate the settings. 
If we add a check to match the count of `:` in original and translated, then we would want to match the count of other symbols as well: `!`, `?`, `.`, `,` and so on. This makes it impossible to create a clean UI with a setting for each of these. 

I was thinking about a setting like this to catch them all:
![image](https://user-images.githubusercontent.com/65488419/125187913-81e23c00-e23a-11eb-9004-e4f22cdbabcb.png)
This way, user can define the symbols they want to be counted and generate a warning if the counts don't match.

Also, to keep the settings to a minimum, I was thinking of dropping the setting "Notify about these words" as it can be redundant. There is already the setting "Warn / prevent saving these words". What do you think about this?

**Comment by vlad-timotei** [comment]
Quoting Peter:

>  I agree a list of characters to check makes it flexible. There is no need to warn for certain verbs, if you have the prevent save list

The above implementation is included in 1.4.
