### ISSUE TITLE
Currently there is no check on the "!" character

### ISSUE THREAD

**Issue by psmits1567** [vlad-timotei/wpgp-tools#16]
It is important that the "!"  is checked for, as it replaces the "." in some cases.
And if that is missing the message should be "Missing !" before indicating "Extra "." 
![afbeelding](https://user-images.githubusercontent.com/28138634/124751953-84395300-df27-11eb-8a39-94211d53fd13.png)

**Comment by vlad-timotei** [comment]
(wrong mention of this ticket above, sorry)
This will be implemented in 1.4
