### ISSUE TITLE
Warning should be given if a plural / singular version of the string is missing

### ISSUE THREAD

**Issue by NekoJonez** [vlad-timotei/wpgp-tools#17]
![image](https://user-images.githubusercontent.com/4569581/124904459-53b7ee80-dfe5-11eb-8be7-426fc6c8bb5d.png)

https://translate.wordpress.org/projects/wp-plugins/wordfence/stable/nl-be/default/?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=10668703&filters%5Btranslation_id%5D=85088012

If it's possible to build in a warning for these kind of suggestions, would be nice.

**Comment by vlad-timotei** [comment]
Thank you for the issue!

GlotPress doesn't let a user to submit an empty translation. However, **it doesn't reject empty plurals when importing**. Maybe you should open an issue about this in GP. 

Until this is fixed mainstream, I added a check only when the pages with translations load, as when you try to submit an empty translation GP will prevent saving.

Adding warning icon, a warning in the editor list and a warning label that doesn't respect user settings on purpose!

**Comment by vlad-timotei** [comment]
![image](https://user-images.githubusercontent.com/65488419/124916051-e747ea00-dffa-11eb-9447-757cc5b5d938.png)
![image](https://user-images.githubusercontent.com/65488419/124916119-f9c22380-dffa-11eb-9203-e4aa8450b925.png)

**Comment by vlad-timotei** [comment]
_The above screenshots are from the developing v 1.4_
