### ISSUE TITLE
Integrate in GlotDict

### ISSUE THREAD

**Issue by Mte90** [vlad-timotei/wpgp-tools#2]
Hi, I am the creator of GlotDict (https://github.com/Mte90/GlotDict) a browser extension for chrome and firefox with more then 500 users http://mte90.tech/ExtStoreStats//data/glotdict.html.
It is mentioned on polyglots handbook and there are various maintainers with me helping the project moving further.
We were thinking that we can join the forces and integrate everything in GlotDict and add you as mantainers.
I don't know if you are also on the wordpress int slack because we have a chat group there.

**Comment by vlad-timotei** [comment]
Thank you for reaching out to me! I feel honored by the proposal. 
I'll start looking into progressively migrating features into GlotDict.
