### ISSUE TITLE
Better document the use of cookies/localstorage and the extension. (Saving of user options)

### ISSUE THREAD

**Issue by NekoJonez** [vlad-timotei/wpgp-tools#26]
So, it turns out that https://github.com/vlad-timotei/wpgp-tools/issues/25 works just fine... But because I cleaned my cookies & browser cache, it """stopped""" working because, to quote @vlad-timotei himself: "It's very resource consuming this feature, so I only want people that need it to enable it."

So, to help new users or users who aren't too use to this tool... Maybe a warning message about the options being saved in a cookie (and maybe have an import/export feature in the long term) would be extremely handy and make the tool more user friendly imho.

**Comment by vlad-timotei** [comment]
Hi! Thanks for the issue!
A small technical detail: WPGPT doesn't use cookies, but LocalStorage - not relevant.

However, the issue is valid - user settings are stored as long as the user doesn't clear their browser data.

There are 2 possible ways of saving the user settings that I'm thinking about:

1. an export/import feature - not quite a fan of this - that file will get lost, and the implementation is not quite straight forward, but it's an option.

2. a drag and drop actionable bookmark that restores your settings. 

Anyway, this should exist in a feature version.

**Comment by NekoJonez** [comment]
Excellent idea's. I just want to add this link for the people who aren't following what the difference between cookies & local storage is. (Like myself, since I'm more of a networking guy than a programmer :P )

https://stackoverflow.com/questions/3220660/local-storage-vs-cookies

**Comment by NekoJonez** [comment]
@vlad-timotei , the 2nd option sounds amazing. Since an import/export feature now that I think of it... It would break over versions and such.

**Comment by vlad-timotei** [comment]
See https://github.com/vlad-timotei/wpgp-tools/tree/one.five#backup--restore-settings
Tested in:
- Chrome
- Edge
- Opera (it tends to select instead of dragging, but it works)
- Brave
- Firefox (UserScript)

**Comment by NekoJonez** [comment]
Excellent, but I do have a question... What will happen if you save an option but you upgrade to another version that has more options?

**Comment by vlad-timotei** [comment]
Very good question. 
The new options will be set to default state if missing from the backup. 

What do you think about checking if the backup version is older and then ask if it should restore or not?

**Comment by vlad-timotei** [comment]
Just pushed [this commit](https://github.com/vlad-timotei/wpgp-tools/commit/fb4128af233e3510f23bb8b5bcf2985d240d6651). User will have to confirm backup restore.

Case A. Version of the backup is **the same** with the version user has installed.
![image](https://user-images.githubusercontent.com/65488419/127499525-09122e8d-4922-4e8e-a698-3487e5a98dab.png)

Case B. Version of the backup is **not the same** with the version user has installed.
![image](https://user-images.githubusercontent.com/65488419/127499632-b0b48d04-df83-4db6-acf5-fb47c300f330.png)

(Date and time have localized format)

**Comment by NekoJonez** [comment]
Now, I see you already implemented something for it... But I would say, options that aren't in the back-up go to default?

**Comment by vlad-timotei** [comment]
That is correct.
