### ISSUE TITLE
Add a check for names that should not be translated

### ISSUE THREAD

**Issue by psmits1567** [vlad-timotei/wpgp-tools#27]
Currently if you save a name of a Theme/plugin or link but have translated it, then no warning is shown when saving.
I would be nice if the tool gave a warning about this problem, but it should be put under a parameter.
Not every locale wants names not to be translated.
The following should be checked.

The second request regarding to this is, that it would also be great if this is checked as well when discovering issues on a page

**Comment by vlad-timotei** [comment]
Per discussion with @psmits1567 this feature is already implemented in [Translation Filler](https://github.com/vibgyj/WPTranslationFiller), so this can be closed.
