### ISSUE TITLE
Build number for testing?

### ISSUE THREAD

**Issue by NekoJonez** [vlad-timotei/wpgp-tools#28]
Would it be possible to show a build number eg in the settings that increases/changes with each commit? 
The goal is for testers to know if they are on the latest build of the development.

**Comment by vlad-timotei** [comment]
I am not aware of any easy automated solution for this unfortunately. But I'm opened to suggestions if there is one.

**Comment by psmits1567** [comment]
There is no automated way to do that. You need to add in the comments of the commit. So every commit should than get an increased number. Or change the name of the branch accordingly. E.g. 1.5 gets the first commit, it will be called 1.5.1 etc.

**Comment by vlad-timotei** [comment]
This would requite too much manual work. I recommend using GitHub Desktop to keep the local files up to date with the latest version from the repo. Checks for new commits and updates the files in one go.
