### ISSUE TITLE
Other translation engine button

### ISSUE THREAD

**Issue by NekoJonez** [vlad-timotei/wpgp-tools#38]
So, this extension adds a feature to go an see what Google Translate gives you. But something I like of the filler tool is that you can also use others like DeepL or Microsofts. Can a future version have an option to choose which translator you want to use?

**Comment by vlad-timotei** [comment]
Hi! Thanks for the idea. I don't plan to overlap features with Translation Filler. If you want automated translations, TF is the way to go, doing a better job than just a simple link to a page. With TF in place, that button of WPGPT is a bit redundant but I'll let it be there for historical purposes. WPGPT doesn't aim to implement automatic translations. So, I will close this, but there's always TF if you want to have translation services in the editor.
