### ISSUE TITLE
Warn on double spaces ALL the time, even when the original has one. 

### ISSUE THREAD

**Issue by NekoJonez** [vlad-timotei/wpgp-tools#45]
Trying to debug and find examples for #44, I wondered: 

What if you agreed in your locale that you aren't going to have double spaces because, e.g., "it looks weird" then you have a strange situation when there is one in the original.

-> When you remove the double space, the tool gives a notification that there is one missing. 
-> When you place a double space somewhere by accident, no warning is given nor a notification. 

So, I think it would be cool if you have a setting where you can say: "Warn on double spaces, regardless of the original" or something of that nature. Where the WPGP-Tools gives off a warning if you have a double space in your translation even when there are double spaces (one or more) in the original.

**Comment by vlad-timotei** [comment]
> What if you agreed in your locale that you aren't going to have double spaces because, e.g., "it looks weird" then you have a strange situation when there is one in the original.

A simple trick would solve that: add `  ` (double space) as a forbidden word in the list of **Prevent saving these words**.

What do you think of this trick instead of adding another setting?

**Comment by NekoJonez** [comment]
I would either document it very well or make a feature of it. Since it might help others to know this ;)

**Comment by vlad-timotei** [comment]
I'll add it to the docs then. :)
I try to keep the complexity of the extension to a minimum and let the user make the best out of it.
I'll close this and update the docs with proper examples of how that feature can be used.
