### ISSUE TITLE
Make going from one page to another easier

### ISSUE THREAD

**Issue by NekoJonez** [vlad-timotei/wpgp-tools#47]
I think it could improve our workflow if we had:

* Key combo to go to: the first page, the previous page, the next page and the last page in the project.
* Have either a dropdown or a box where you can enter from which page you want to start. -> This would make it easier to "clean" projects (improving old translations.) If you left off on page 50 or something... It would save you some clicking / changing the url.

**Comment by NekoJonez** [comment]
Also talked about in Slack:

Keycombo:

Shift + P for the previous page 
Shift + N for the next page

https://defkey.com/search?irq=shift%2Bp -> Shift+P was a shortcut in Opera, but not used anymore.
https://defkey.com/search?irq=shift%2Bn -> Has no function in a browser.

Maybe these too?

Shift + S for "start" or first page?
Shift + L for "last" or final page?

https://defkey.com/search?irq=shift%2Bs -> Has uses in browser, but only in specific apps like Office & Google Drive... Where this tool doesn't do something.
https://defkey.com/search?irq=shift%2Bl -> No browser use.

For the 2nd one, as we talked about in Slack, I think a dropdown would maybe be glitchy/difficult to create... So, just a box to fill in the page number and go will be easier. Since that number is just a number variable in the URL.

**Comment by vlad-timotei** [comment]
I agree a quicker way of navigating to a certain page can be helpful. Will add this to the future features. 
I am not fond of numerous keyboard shortcuts, but will leave this open for feedback as well.
Thank you for your ideas!

**Comment by vlad-timotei** [comment]
![easy_nav](https://user-images.githubusercontent.com/65488419/141653433-2ac0e94a-86df-48b2-b39e-8dbe01b5d012.gif)

A new EasyNav feature has been implemented - a dropdown of pages.
For now, the keyboard shortcuts would be an overkill IMO, so maybe later.

**Comment by psmits1567** [comment]
Nice feature, but adding a new shortcut makes it not better to use in my opinion. You would need to remember to many of them to make it usefull
