### ISSUE TITLE
Extend checks for additional "." to also include other punctuation marks.

### ISSUE THREAD

**Issue by NekoJonez** [vlad-timotei/wpgp-tools#48]
From a discussion of #46 in DM's in Slack...

Currently, WPGP only checks if you add an additional "." at the string, but it doesn't check for other punctuation marks. I think this could be a nice extension of the toolset.

**Comment by vlad-timotei** [comment]
I'm not 100% convinced this is necessary.
`.` is so easily added at the end of the string by reflex, but `!` and `?` are more of a choice of the translator and if they want to use it, I wouldn't consider this a mistake.

I'll leave this open while we get more feedback on this.

**Comment by NekoJonez** [comment]
Agreed, it's only in edge cases... Especially when you translate a string that sounds more like a question in your language. (<- As example)

**Comment by vlad-timotei** [comment]
Closing this for now as translators can intentionally add `?` or `!` at the end of a string if they consider necessary.
