### ISSUE TITLE
If you have show history activated, then when you go into WordPress history, the label for histories are still shown

### ISSUE THREAD

**Issue by psmits1567** [vlad-timotei/wpgp-tools#49]
The history labels are shown within a page, when old records exists.
If you go into the editor of such a record, and select GlotPress history, the labels that show the count of history items are still shown. This is a bit of overkill, as you do see all the history within the list.
When within the GlotPress history, those labels can be left out as they have no purpose
![image](https://user-images.githubusercontent.com/28138634/140493469-24b54419-0e31-4e93-92ec-42372737e60d.png)

**Comment by psmits1567** [comment]
I found this because I have the same in WP translation Filler after fixing an issue NekoJonez reported

**Comment by vlad-timotei** [comment]
I thought we discussed this and the last setting here was introduced.
![image](https://user-images.githubusercontent.com/65488419/140502285-6788f7b2-85ee-4c9b-9ac1-8128037cc3c0.png)
Do you have it set to Yes or No?

I personally find translation status useful everywhere, but I understand why it might not fit into everyone's workflow. 
Let me know if the setting is not working properly. I cannot reproduce this with the setting off.

**Comment by psmits1567** [comment]
The setting is not working, I altered the setting to NO and refreshed the page. It still shows history

**Comment by psmits1567** [comment]
https://translate.wordpress.org/projects/wp-plugins/jetpack/stable/nl/default/?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=611132&sort%5Bby%5D=translation_date_added&sort%5Bhow%5D=asc

**Comment by psmits1567** [comment]
current setting
![image](https://user-images.githubusercontent.com/28138634/140505815-3780d5c4-9efb-4eb8-b2f1-d6322bab698c.png)
![image](https://user-images.githubusercontent.com/28138634/140505892-f8374431-23d4-41ba-a79d-8e2cced569bb.png)
![image](https://user-images.githubusercontent.com/28138634/140505946-98fd2bd6-4900-46e2-94a4-ad378f20a9a7.png)
![image](https://user-images.githubusercontent.com/28138634/140506015-8a7f17ed-b406-4c2e-bba1-af7f1e7f30c4.png)
![image](https://user-images.githubusercontent.com/28138634/140506062-f4c13a4e-d156-4f61-a417-4e7c8a13a52d.png)
Link shown
https://translate.wordpress.org/projects/wp-plugins/jetpack/dev/nl/default/?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=599997&sort%5Bby%5D=translation_date_added&sort%5Bhow%5D=asc

**Comment by psmits1567** [comment]
This is the link I click within the editor
https://translate.wordpress.org/projects/wp-plugins/jetpack/stable/nl/default/?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=611132&sort%5Bby%5D=translation_date_added&sort%5Bhow%5D=asc

**Comment by vlad-timotei** [comment]
Either
- use GlotDict as well OR
- change the `Also using GlotDict?` setting to `No.` 

This fixes the issue, as confirmed by you.
