### ISSUE TITLE
The string count is shown twice?

### ISSUE THREAD

**Issue by NekoJonez** [vlad-timotei/wpgp-tools#5]
![image](https://user-images.githubusercontent.com/4569581/123265380-484fc800-d4fb-11eb-9bb7-42e33d3322bb.png)

Is it me or is the "original string" and the "current string" shown twice?

**Comment by NekoJonez** [comment]
I notice that this mostly happens in plugins and almost never in themes.

**Comment by NekoJonez** [comment]
Welp, I yeeted TranslationFiller from my browser and it seems to not happen anymore... 

Before you close this, maybe it would be interesting to check if that extension is present and then maybe hide yours to avoid dupes?

**Comment by vlad-timotei** [comment]
The thing is WPGPT **doesn't** have any such functionality 🤣 I don't count words nor characters. I try not to overlap features with other extensions, but something from WPGPT might generate something that makes GD to duplicate that thing....

**Comment by vlad-timotei** [comment]
I'm keeping this open to debug where the problem comes from. If you find a string where you see the problem, please share a link. Also let me know exactly what extensions are active, so I can try to replicate. Thanks.

**Comment by vlad-timotei** [comment]
Closing this for now, but feel free to comment if you can replicate the issue with WPGPT enabled, but not with WPGPT disabled. Most probably it's not a WPGPT issue.
