### ISSUE TITLE
Ending `&ZeroWidthSpace;` in original generates apparently wrong warning

### ISSUE THREAD

**Issue by NekoJonez** [vlad-timotei/wpgp-tools#51]
https://translate.wordpress.org/projects/wp-plugins/redirect-redirection/stable/nl-be/default/?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=12203654&filters%5Btranslation_id%5D=89469374

The original asks a ":" but I get a warning that I added an additional ":"

**Comment by vlad-timotei** [comment]
Hi! Thank you for the issue. 
The original doesn't end with `:` even though it looks like it does.
It ends with `&ZeroWidthSpace;` and that breaks the checker. That character should not be there IMO, as the languages that don't care about that will not translate it, and the languages that care about these typographic rules will add it regardless of its presence. But in a string, it's not visible in the translation interface.

![image](https://user-images.githubusercontent.com/65488419/141652347-ca1c0ea0-77e1-47ed-96c4-da2a78775535.png)

If these cases are often, I *could* implement an additional check for such things to ignore them.

**Comment by vlad-timotei** [comment]
Since this seems to be an exception, will close this, as it's not efficient to check for this character. As stated above, IMHO it should not be used in originals.
