### ISSUE TITLE
When the tool finds "1 current" on a page, it should give a warning.

### ISSUE THREAD

**Issue by NekoJonez** [vlad-timotei/wpgp-tools#53]
Various times, I find plugins that have more translated strings then current. Hunting these down is made easier with this extension and the history feature.
Now, I would find it quite handy if this tool gave some sort of warning (those triangle warnings maybe?) when there are 2 currents for a string. 
That way you can find these

![image](https://user-images.githubusercontent.com/4569581/151780416-4ec9c6b1-8b75-445a-a55a-9f62e74af102.png)

Even easier. 

I left this one alone for testing this feature: 

https://translate.wordpress.org/projects/wp-plugins/events-made-easy/stable/nl-be/default/?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=12843760&sort%5Bby%5D=translation_date_added&sort%5Bhow%5D=desc&historypage

Edit: it could also give some sort of warning at the top where the numbers are to draw the attention that those numbers don't match...? I would only put a check there if the translated > all. Because if you display a warning when all > translated, you'd trigger a warning every not 100% translated plugin :P

**Comment by NekoJonez** [comment]
Another one: https://translate.wordpress.org/projects/wp-plugins/events-made-easy/stable/nl/default/?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=12843760&sort%5Bby%5D=translation_date_added&sort%5Bhow%5D=desc&historypage

**Comment by vlad-timotei** [comment]
Hi and thank you for the issue!
Although I don't understand how this is possible (having 2 current strings), I've seen it enough to make a feature for it. :) 

Let's make use of the History Count tool and add some checks.

-  If row has current state
-  If row's history count has current > 1

then

- display a ❌ inside the history count label
- make the label background different

To make things easier for a GTE/PTE, on page load and on every save action, count the ❌ on that page and if found, display a flag near `Translated (x)`. 



>  it could also give some sort of warning at the top where the numbers are to draw the attention that those numbers don't match...? I would only put a check there if the translated > all. Because if you display a warning when all > translated


For now, I don't understand how those counts work in relationship witht this issue, so for now, I won't take in consideration that aspect, but maybe in the future that could be a check as well. Yet, hopefully, the issue will be fixed upstream. 😃

**Comment by NekoJonez** [comment]
Like I confirmed on Slack, your solution looks amazing. 
The gif of it would do nicely.

I think it would help us editors till this is fixed upstream

**Comment by vlad-timotei** [comment]
Some screenshots:

![h2](https://user-images.githubusercontent.com/65488419/152685124-260dc2c1-3a89-4f2b-837d-e2e7fe55453c.PNG)
![h1](https://user-images.githubusercontent.com/65488419/152685123-5f4663bb-46c4-46d1-a2c7-54cd70f04fc1.PNG)
![h3](https://user-images.githubusercontent.com/65488419/152685125-808a8889-cd04-4e17-a6ed-285dde021e55.PNG)

**Comment by vlad-timotei** [comment]
Fixed in https://github.com/vlad-timotei/wpgp-tools/commit/10c29ed57f2886745c15461f466f5b881e897d42 
Will be available in 2.0.1 release.
