### ISSUE TITLE
Tools or Tool settings?

### ISSUE THREAD

**Issue by NekoJonez** [vlad-timotei/wpgp-tools#55]
I would like to have a small discussion. I was helping a new translator who installed WPGP and she said: "Why is it plural? Since, you are adjusting the settings of the WPGP Tools? And not adjusting the settings of multiple tools right?"

So, the menu item... Plural or singular?

**Comment by vlad-timotei** [comment]
Thank you for the issue!
Will rename it to WPGPT Settings to make that more clear.
