### ISSUE TITLE
If WPGPT is active then if the original has a lot of suggestions from TM, the content box is moved up to far

### ISSUE THREAD

**Issue by psmits1567** [vlad-timotei/wpgp-tools#58]
If WPGPT is active and a translation contains a lot of suggestions from TM or suggestions from consistency, the content box is moved up to far. After this you cannot read the original anymore, you need to scroll the content box down to see the original again.
If WPGPT is not active, then this is not happening.
Scrolling is fine, but the original should always be visible.
Below an example what I see happening
![image](https://user-images.githubusercontent.com/28138634/155885530-cc8ce901-2653-4b37-8d23-ea3125b9b091.png)

**Comment by vlad-timotei** [comment]
Will close this. Let me know if this is still an issue with the new design.
