### ISSUE TITLE
Tool doesn't always recognizes URL changes.

### ISSUE THREAD

**Issue by NekoJonez** [vlad-timotei/wpgp-tools#6]
I'm currently also working on decreasing the nl_NL-formal strings and the script didn't give me a warning when I edited this fuzzy:

https://translate.wordpress.org/projects/wp-themes/benevolent/nl/formal/?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=3125244&filters%5Btranslation_id%5D=85008978

The URL was changed and I tried to save it without changing it and the tool didn't stop nor warn me.

**Comment by NekoJonez** [comment]
Another example in the same theme project:

![image](https://user-images.githubusercontent.com/4569581/123266338-328ed280-d4fc-11eb-8b28-f7f751775af7.png)

**Comment by vlad-timotei** [comment]
Hi, @NekoJonez 
Thank you for the issue. WPGPTools doesn't check for URL changes at all.
It might be a good idea for a future feature, but I think GlotPress has already implemented this... It should have give you a warning... strange. 

How would you like to see this feature working?

**Comment by NekoJonez** [comment]
Well, GlotDict gave me the warning actually... But I think it could be handy like you do with punctuation marks, that you get a message "check url" or something of that nature to nudge people to check if the URL is correctly translated. Since, quite rarely an url differs from the source... This way we also could easily find strings where http:// needs to be changed in https:// and such things...

Thinking out loud here.

**Comment by vlad-timotei** [comment]
If it's in GlotDict, then I don't have any plans to overlap the feature. And I actually think GlotPress has something similar. Better to improve in those places than to implement a baby feature here that does what those already do. 

I don't plan to develop anything that is in GlotDict or GlotPress, as the long term plan is to merge features in GD/GP. 😄

**Comment by NekoJonez** [comment]
Whoops, apologies! I totally meant GlotPress. >.> Jeez, moment of being inattentive.. :/

**Comment by vlad-timotei** [comment]
If GlotPress did it, then yay! It works and it will let us know when we do mistakes haha.

**Comment by NekoJonez** [comment]
I have an idea to improve the plugin that's somewhat related with this ticket but I'm going to make a new one for it... To keep it seperated.
