### ISSUE TITLE
Possible confusing warning with end spaces

### ISSUE THREAD

**Issue by NekoJonez** [vlad-timotei/wpgp-tools#61]
https://translate.wordpress.org/projects/wp-plugins/wpvivid-backuprestore/stable/nl-be/default/?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=10222513&filters%5Btranslation_id%5D=93089598

A lot in this plugin, strings that end on a ":" have an end space. But, not this string. The warning I got is that the translation is missing either a ".","!" or "?" ... But it was missing nothing, it was an additional end space.

**Comment by vlad-timotei** [comment]
Hi! I can't reproduce this. I added an additional space after the semicolon and I got the right warning.
![image](https://user-images.githubusercontent.com/65488419/161397787-a887d15e-b43e-4b8f-956b-d48c084c5777.png)
Let me know how to reproduce this.
Thanks.

**Comment by NekoJonez** [comment]
I'm going to close this for now... I re-tested it and I wasn't able to reproduce it myself... :o 
So, maybe so freaky edge case?
