### ISSUE TITLE
Wrong identification of the plugin/theme name

### ISSUE THREAD

**Issue by NekoJonez** [vlad-timotei/wpgp-tools#62]
https://translate.wordpress.org/projects/wp-themes/construction-landing-page/nl-be/default/?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=4808803&filters%5Btranslation_id%5D=93089810

When bulk replacing from the consistency tool... WPGP doesn't replaces strings likes this. As soon as "plugin name" is in the comment... It's blocked. 
This is a double edged sword. It's a good idea to block it, since not every dev comments the same. BUT, then you have moments like this. Where the dev comments that a placeholder is the plugin name so nothing to worry about but WPGP stops you... 

Maybe food for thought?

**Comment by vlad-timotei** [comment]
Thank you for the issue. Will fix this.
In 2.0.1 if a `%` is present in the comment (meaning it explains the placeholder) it will not be blocked.
