### ISSUE TITLE
-1 current is possible on history label

### ISSUE THREAD

**Issue by NekoJonez** [vlad-timotei/wpgp-tools#67]
"-1 current" is possible to show when you go to the string history page of an untranslated string that has all previous ones rejected. When you translate it there, WPGP shows "-1 current".

**Comment by NekoJonez** [comment]
![image](https://user-images.githubusercontent.com/4569581/192481967-516e2879-e099-4732-bb74-308a39e2d8eb.png)

**Comment by vlad-timotei** [comment]
Fixed. Will be included in 2.1.1
