### ISSUE TITLE
Don't hide buttons on translated strings.

### ISSUE THREAD

**Issue by NekoJonez** [vlad-timotei/wpgp-tools#7]
So, when you open a translated (current) string, the handy buttons for a consistency check, perma link... are gone. 

I think it would be handy to still have them since if you quickly need the link to the translation to submit a ticket of a typo... it could be handy to have that button if you already translated it.

**Comment by vlad-timotei** [comment]
Hi, @NekoJonez 
Thank you for the issue. 
Indeed, the the search tabs do not load the Consistency tools (search and others), as these are supposed to be minimalistic views just for documentation purposes. Also to prevent nested search results.

But the Quick Links maybe could be there.... My fear is that someone will keep opening nested pages and then they close the main page and 50 tabs close with that as well... and they are not aware of that... not so ideal. 

Will think about this.

**Comment by NekoJonez** [comment]
Yeah, UI is a fine line to develop for... But I totally agree in what you are saying.

**Comment by vlad-timotei** [comment]
The results page now will load ALL Consistency tools, except Search Form - to prevent too many nested pages.

Consistency tools loaded:
- Consistency button
- Quick Links
- GT button

Can you please test [branch one.four](https://github.com/vlad-timotei/wpgp-tools/tree/one.four) and provide some feedback on this? Thank you!

**Comment by NekoJonez** [comment]
How do I install the test branch...?

**Comment by vlad-timotei** [comment]
1. Go [here](https://github.com/vlad-timotei/wpgp-tools/tree/one.four)
2. Click the green button **Code** and then **Download Zip**
3. Extract the zip
4. Open Chrome extensions chrome://extensions/ or edge://extensions/ or opera://extensions/  and disable or delete WPGPT 1.3 (the new one will still show up as 1.3, so not to mix them up)
5. Then use Load Unpacked button and point to the wpgp-tools-one.four\src\ folder
6. That's it! 

If you go to the Settings page and you see something called String history, then you have the new in work version.
Thanks for testing!

**Comment by NekoJonez** [comment]
Just tested it out and it works flawlessly imo and in my testing.

**Comment by vlad-timotei** [comment]
Awesome! 🚀 Thanks for testing. Then I'm going to close this.
