### ISSUE TITLE
Which features are GlotDict/WPGP

### ISSUE THREAD

**Issue by NekoJonez** [vlad-timotei/wpgp-tools#70]
With the option to use WPGP in GlotDict mode, its possibly unclear for users which feature comes from which extension... In other words, where to post feature requests and/or bug reports.

**Comment by vlad-timotei** [comment]
Features that have been moved from WPGPT to GlotDict are now disabled by default in WPGPT (you need to enable a setting to activate them) but in a future release that setting will not be available any more.

The idea behind this is that we eventually want GlotPress itself (GlotPress helpers plugins) to have all these features and lately we have seen masive improvements there and some features will fade away from GlotDict as well when they're being implemented on w.org. 

As for a user not knowing where to post bug reports - it's okay if they end up in the wrong repo - we're here to sort things out if that happens. 😃
